/**
 * Auto-generated by openapi-typescript. DO NOT EDIT.
 * Placeholder — will be generated when backend Go exposes OpenAPI schema.
 * Run: npm run generate:types
 */
export type paths = Record<string, never>;
export type components = Record<string, never>;
